name: secret-santa-bot
services:
- name: worker
  github:
    branch: main
    repo: USERNAME/REPO_NAME # Update this or select in UI
    deploy_on_push: true
  dockerfile_path: Dockerfile
  health_check:
    http_path: /health
  envs:
  - key: DISCORD_TOKEN
    scope: RUN_TIME
    value: "PLACEHOLDER_TOKEN"
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: DB_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: DB_NAME
    scope: RUN_TIME
    value: ${db.DATABASE}
  - key: DB_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
    type: SECRET
  - key: DB_PASSWORD
    scope: RUN_TIME
    value: ${db.PASSWORD}
    type: SECRET
  - key: SETUP_DATABASE
    scope: RUN_TIME
    value: "true"
databases:
- engine: PG
  name: db
  version: "12"
